muzar_bazaar_homepage:
    pattern:  /
    defaults: { _controller: MuzarBazaarBundle:Default:index }


muzar_bazaar_item:
    resource: "@MuzarBazaarBundle/Controller/ItemController.php"
    prefix:   /api
    defaults: { _format: json }
    type:     annotation

muzar_bazaar_category:
    resource: "@MuzarBazaarBundle/Controller/CategoryController.php"
    prefix:   /api
    defaults: { _format: json }
    type:     annotation


muzar_bazaar_item_edit:
    path:      /ads/edit/{id}
    defaults:  { _controller: muzar_bazaar.controller.item_edit:defaultAction, id: null }