parameters:


services:

    muzar_bazaar.model.entity_listener.category:
        class: Muzar\BazaarBundle\Entity\CategoryListener
        arguments: [@muzar_bazaar.nsm.category]

    muzar_bazaar.nsm.category.config:
        class: DoctrineExtensions\NestedSet\Config
        arguments: [@doctrine.orm.entity_manager, Muzar\BazaarBundle\Entity\Category]
        calls:
            - [setRootFieldName, [null]]



    muzar_bazaar.nsm.category:
        class: DoctrineExtensions\NestedSet\Manager
        arguments: [@muzar_bazaar.nsm.category.config]



    muzar_bazaar.model_service.item:
        class: Muzar\BazaarBundle\Entity\ItemService
        arguments: [@doctrine.orm.entity_manager, @fos_elastica.manager, @muzar_bazaar.model_service.category]

    muzar_bazaar.model_service.category:
        class: Muzar\BazaarBundle\Entity\CategoryService
        arguments: [@doctrine.orm.entity_manager, @muzar_bazaar.nsm.category]


    muzar_bazaar.controller.item:
        class: Muzar\BazaarBundle\Controller\ItemController
        arguments: [@router, @form.factory, @doctrine.orm.entity_manager, @muzar_bazaar.model_service.item]

    muzar_bazaar.controller.category:
        class: Muzar\BazaarBundle\Controller\CategoryController
        arguments: [@router, @doctrine.orm.entity_manager, @muzar_bazaar.model_service.category]



    muzar_bazaar.serializer.event_subscriber:
        class: Muzar\BazaarBundle\Serializer\EventSubscriber
        arguments: [@router]
        tags:
            - { name: jms_serializer.event_subscriber, connection: default }
