#%RAML 0.8
title: Muzar.cz
baseUri: http://api.muzar.cz/{version}
version: 0.1

/ads:
  get:
    queryParameters:
      startId:
        type: integer
        example: 4
      limit:
        type: integer
        example: 4
    description: Loads list of ads.
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "meta": {
                  "params": {
                    "limit": 6
                  },
                  "nextLink": "/ad?startId=4",
                  "total": 128
                },
                "data": [
                  {
                    "id": 1,
                    "name": "Fender Telecaster Mexico",
                    "image_url": "http://lorempixel.com/300/200",
                    "district": "Olomoucký kraj",
                    "price": 13000,
                    "description": "",
                    "created": "2013-12-12 12:45:30",
                    "url": "/ads/1"
                  },
                  {
                    "id": 2,
                    "name": "Fender Precision Bass",
                    "image_url": "http://lorempixel.com/300/200",
                    "district": "Královehradecký kraj",
                    "price": 20000,
                    "description": "",
                    "created": "2013-12-12 12:45:30",
                    "url": "/ads/2"
                  }
                ]
              }
  /{id}:
    uriParameters:
      id:
        type: integer
        example: 2
    get:
      description: Loads ad by id.
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "meta": {
                  },
                  "data": {
                    "id": 2,
                    "name": "Fender Telecaster Mexico",
                    "status": "active",
                    "image_url": "http://placehold.it/300x200/008&text=2",
                    "district": "Olomoucký kraj",
                    "price": 13000,
                    "description": "",
                    "created": "2013-12-12 12:45:30",
                    "categories": [
                      {
                        "id": 7,
                        "strId": "akusticke-a-klasicke-kytary",
                        "name": "Akustické a klasické kytary"
                      }
                    ],
                    "url": "/ads/2"
                  }
                }


/suggestions:
  get:
    description: Fulltext autosuggester.
    queryParameters:
      query:
        type: string
        example: akusticke
        required: true
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "meta": {
                  "params": {
                    "query": "akustic"
                  }
                },

                "data": {
                  "categories": [
                    {
                      "strId": "akusticke-a-klasicke-kytary",
                      "name": "Akustické a klasické kytary",
                      "path": ["Kytary", "Akustické a klasické kytary"]
                    },
                    {
                      "strId": "akusticke-kontrabasy",
                      "name": "Akustické a kontrabasy",
                      "path": ["Baskytary", "Akustické a kontrabasy"]
                    }
                  ],
                  "ads": [
                    {
                      "id": 1,
                      "name": "Akusticka kytara Jumbo",
                      "image_url": "http://lorempixel.com/300/200",
                      "district": "Olomoucký kraj",
                      "price": 900,
                      "description": "",
                      "created": "2013-12-12 12:45:30",
                      "url": "/ads/10"
                    },
                    {
                      "id": 2,
                      "name": "Kontrabas akusticky, preklizka",
                      "image_url": "http://lorempixel.com/300/200",
                      "district": "Královehradecký kraj",
                      "price": 20000,
                      "description": "",
                      "created": "2013-12-12 12:45:30",
                      "url": "/ads/2"
                    }
                  ]
                }
              }


/categories:
  /tree:
    get:
      description: Loads category tree.
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "meta": {
                  },
                  "data":  [
                    {
                      "strId": "kytary",
                      "name": "Kytary",
                      "children": [
                        {
                          "strId": "elektricke-kytary",
                          "name": "Elektricke kytary",
                          "children": [
                            {
                              "strId": "strat",
                              "name": "Stratocaster"
                            },
                            {
                              "strId": "tele",
                              "name": "Telecaster"
                            },
                            {
                              "strId": "lp",
                              "name": "LesPaul"
                            },
                            {
                              "strId": "sg",
                              "name": "SG"
                            },
                            {
                              "strId": "v-hardandheavy",
                              "name": "V, hard and heavy"
                            },
                            {
                              "strId": "semiakustika",
                              "name": "Semiakustické kytary"
                            },
                            {
                              "strId": "vicestrunne",
                              "name": "7 a více strunné"
                            },
                            {
                              "strId": "ostatni-tvary",
                              "name": "Ostatní tvary"
                            }
                          ]
                        },
                        {
                          "strId": "akusticke-a-klasicke-kytary",
                          "name": "Akustické a klasické kytary",
                          "children": [
                            {
                              "strId": "klasicka-kytara",
                              "name": "Klasická kytara"
                            },
                            {
                              "strId": "dvanactistrunna",
                              "name": "12 - strunná"
                            },
                            {
                              "strId": "jumbo-grand-dreadnaut",
                              "name": "Jumbo/grand/dreadnaut"
                            }
                          ]
                        },
                        {
                          "strId": "ostatni-strunne",
                          "name": "Ostatní strunné",
                          "children": [
                            {
                              "strId": "ukulele",
                              "name": "Ukulele"
                            },
                            {
                              "strId": "banjo",
                              "name": "Banjo"
                            },
                            {
                              "strId": "mandolina",
                              "name": "Mandolina"
                            }
                          ]
                        },
                        {
                          "strId": "levoruke",
                          "name": "Levoruké",
                          "children": [
                            {
                              "strId": "levoruke-elektricke",
                              "name": "Elektrické kytary"
                            },
                            {
                              "strId": "levoruke-akusticke",
                              "name": "Akustické kytary"
                            }
                          ]
                        },
                        {
                          "strId": "modeling-usb-hybrid",
                          "name": "Modeling, usb, hybrid"
                        },
                        {
                          "strId": "prislusenstvi",
                          "name": "Příslušenství"
                        },
                        {
                          "strId": "snimace",
                          "name": "Snímače"
                        },
                        {
                          "strId": "kytarove-aparaty",
                          "name": "Kytarové aparáty",
                          "children": [
                            {
                              "strId": "komba",
                              "name": "Komba"
                            },
                            {
                              "strId": "zesilovace-hlavy",
                              "name": "Zesilovače a hlavy"
                            },
                            {
                              "strId": "reproboxy",
                              "name": "Reproboxy"
                            },
                            {
                              "strId": "prislusenstvi-nahradnidily",
                              "name": "Příslušenství a nahradní díly"
                            }
                          ]
                        },
                        {
                          "strId": "kytarove-efekty",
                          "name": "Kytarové efekty",
                          "children": [
                            {
                              "strId": "multiefekty",
                              "name": "Multiefekty"
                            },
                            {
                              "strId": "synth",
                              "name": "Synťáky"
                            },
                            {
                              "strId": "efektove-pedaly",
                              "name": "Efektové pedály"
                            },
                            {
                              "strId": "wah-wah",
                              "name": "Wah Wah"
                            },
                            {
                              "strId": "volume",
                              "name": "Volume"
                            },
                            {
                              "strId": "rackove-efekty",
                              "name": "Rackové efekty"
                            },
                            {
                              "strId": "sitove-efekty",
                              "name": "Síťové efekty"
                            },
                            {
                              "strId": "pedalboardy",
                              "name": "Pedalboardy"
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "strId": "baskytary",
                      "name": "Baskytary",
                      "children": [
                        {
                          "strId": "elektricke-basy",
                          "name": "Elektricke basy"
                        },
                        {
                          "strId": "akusticke-kontrabasy",
                          "name": "Akustické a kontrabasy"
                        }
                      ]
                    },
                    {
                      "strId": "bici",
                      "name": "Bicí"
                    },
                    {
                      "strId": "klavesy",
                      "name": "Klávesy"
                    },
                    {
                      "strId": "dechove-nastroje",
                      "name": "Dechové nástroje"
                    },
                    {
                      "strId": "smyccove-nastroje",
                      "name": "Smyčcové nástroje"
                    },
                    {
                      "strId": "zvukova-technika",
                      "name": "Zvuková technika"
                    },
                    {
                      "strId": "svetelna-technika",
                      "name": "Světelná technika"
                    },
                    {
                      "strId": "djs",
                      "name": "Djs"
                    }
                  ]
                }
