parameters:
#    muzar_product_catalog.example.class: Muzar\ProductCatalogBundle\Example

services:
#    muzar_product_catalog.example:
#        class: %muzar_product_catalog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
